export const GET_UPCOMING_WEBINARS = 'GET_UPCOMING_WEBINARS'
export const GET_PAST_WEBINARS = 'GET_PAST_WEBINARS'
export const GET_WEBINAR = 'GET_WEBINAR'

export const SIGN_UP = 'SIGN_UP'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'

export const REMOVE_ERROR = 'REMOVE_ERROR'
export const SET_ERROR = 'SET_ERROR'